# Generated by Django 5.2.4 on 2025-07-25 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airplane", "0002_airplane_enabled_alter_seat_column"),
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="airplane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flights",
                to="airplane.airplane",
            ),
        ),
    ]
