# Generated by Django 5.2.4 on 2025-07-31 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_flight_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='duration',
        ),
    ]
