# Generated by Django 5.2.4 on 2025-10-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_remove_flight_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código Aeropuerto'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre Aeropuerto'),
        ),
    ]
