# Generated by Django 5.2.4 on 2025-07-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airplane", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="seat",
            name="column",
            field=models.CharField(max_length=1),
        ),
    ]
