# Generated by Django 5.2.4 on 2025-07-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airplane", "0002_airplane_enabled_alter_seat_column"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airplane",
            name="capacity",
        ),
    ]
