# Generated by Django 5.2.4 on 2025-07-30 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0003_remove_airplane_capacity'),
        ('reservations', '0002_alter_passenger_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsegment',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airplane.seat'),
        ),
    ]
