# Generated by Django 5.2.4 on 2025-08-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_flightsegment_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsegment',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
