# Generated by Django 5.2.4 on 2025-07-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='document_type',
            field=models.CharField(blank=True, choices=[('dni', 'DNI'), ('passport', 'Pasaporte')], max_length=50, null=True),
        ),
    ]
