# Generated by Django 5.2.4 on 2025-08-04 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='order',
        ),
    ]
